### ISSUE TITLE
Slowdown chrome/chromium experience

### ISSUE THREAD

**Issue by rcspam** [smeeckaert/chromoji#6]
I.E.:  When enter mouse in youtube video running, the video lags...
        When move mouse on some interactive menus, the update of  target is very slow...
OOps! I forget the chrome/chromium statup is very sow...

**Comment by smeeckaert** [comment]
Yeah, i've experienced a lot of lag these days, i will look into it whenever i can.

**Comment by smeeckaert** [comment]
It will be good with 1.0.13
