### ISSUE TITLE
Extension breaks Google Chrome help pages.

### ISSUE THREAD

**Issue by I-Hope-That-You-Understand** [smeeckaert/chromoji#7]
Any pages at "support.google.com" are severely broken due to this extension.  Hopefully this can be fixed!  I like having a little menu to more easily enter emojies on Twitter.

Figure 1: Extension enabled, scrolled about halfway.
http://i.imgur.com/YlHujiZ.png

Figure 2: Extension disabled, scrolled to bottom.
http://i.imgur.com/6VWHDKG.png

**Comment by smeeckaert** [comment]
Will be corrected in 1.0.13.
