### ISSUE TITLE
Update to add new Google Emojis

### ISSUE THREAD

**Issue by LinkofHyrule89** [smeeckaert/chromoji#9]
So google just added more Emoji (and changed a few of them) in the Android N preview based on Unicode 9 it would be great to see them updated in the extension!

**Comment by smeeckaert** [comment]
I will look into it, i need some data on the emojis before hand and i have to make sure i can file the image sources for these emojis !

**Comment by smeeckaert** [comment]
Unicode 9 is now supported. Thanks for the feedback !
